### ISSUE TITLE
Don't expose variables with invalid names to subsequent inputs

### ISSUE THREAD

**Issue by bisgardo** [bisgardo/github-action-echo#4]
Example:

```
    - uses: bisgardo/github-action-echo@v1
      id: my_step
      with:
        with-dash: x
        next: y
```

When processing `next`, the action will attempt to define a variable named `with-dash` which is not a valid name in Bash: An error like `/bin/bash: line 1: with-dash=x: command not found` will be printed to stdout and included in the output value for `next`.

The solution is to check if a variable name is valid and not do the assignment if it isn't.
